language: objective-c
cache: cocoapods
osx_image: xcode7.3
xcode_workspace: ShadowsocksX2.xcworkspace
xcode_scheme: ShadowsocksX2
before_install:
  - gem install cocoapods -v '1.0.1'
install:
  - pod install --repo-update --verbose
before_script:
  - cd shadowsocks-libev && ./configure --with-openssl=/usr/local/opt/openssl/ && cd ..
script: set -o pipefail && xcodebuild build -workspace ShadowsocksX2.xcworkspace -scheme ShadowsocksX2|xcpretty
